import type { Listing, Profile, Vehicle } from '@/types';

export const seedListings: Partial<Listing>[] = [
  // Colombo listings
  {
    id: 'seed-1',
    owner_id: 'owner-1',
    title: 'Colombo City Centre Parking',
    description: 'Secure underground parking in the heart of Colombo. This premium parking facility offers 24/7 security, CCTV surveillance, and easy access to major commercial areas.',
    address: 'No. 123, York Street, Colombo 01',
    city: 'Colombo',
    district: 'Colombo',
    latitude: 6.9271,
    longitude: 79.8612,
    price_per_hour: 350,
    price_per_day: 2500,
    amenities: ['CCTV', 'Security', 'Covered', 'EV Charging', 'Elevator'],
    vehicle_types: ['car', 'motorcycle'],
    total_spaces: 50,
    available_spaces: 12,
    operating_hours_start: '06:00',
    operating_hours_end: '23:00',
    is_24_hours: false,
    status: 'approved',
    verification_status: 'verified',
    rating: 4.8,
    review_count: 156,
  },
  {
    id: 'seed-2',
    owner_id: 'owner-2',
    title: 'Galle Face Hotel Parking',
    description: 'Premium parking near Galle Face Green. Perfect for beach lovers and business travelers.',
    address: 'Galle Road, Colombo 03',
    city: 'Colombo',
    district: 'Colombo',
    latitude: 6.9196,
    longitude: 79.8423,
    price_per_hour: 500,
    price_per_day: 3500,
    amenities: ['Valet', 'CCTV', 'Security', 'Car Wash'],
    vehicle_types: ['car'],
    total_spaces: 30,
    available_spaces: 5,
    operating_hours_start: '00:00',
    operating_hours_end: '23:59',
    is_24_hours: true,
    status: 'approved',
    verification_status: 'verified',
    rating: 4.9,
    review_count: 89,
  },
  {
    id: 'seed-3',
    owner_id: 'owner-3',
    title: 'Liberty Arcade Parking',
    description: 'Modern parking facility in Colombo 03 with easy access to shops and restaurants.',
    address: 'Liberty Arcade, Colombo 03',
    city: 'Colombo',
    district: 'Colombo',
    latitude: 6.9149,
    longitude: 79.8523,
    price_per_hour: 400,
    price_per_day: 2800,
    amenities: ['CCTV', 'Security', 'Elevator', 'Waiting Area'],
    vehicle_types: ['car', 'motorcycle'],
    total_spaces: 75,
    available_spaces: 22,
    operating_hours_start: '07:00',
    operating_hours_end: '22:00',
    is_24_hours: false,
    status: 'approved',
    verification_status: 'verified',
    rating: 4.6,
    review_count: 203,
  },
  {
    id: 'seed-4',
    owner_id: 'owner-4',
    title: 'Borough Lane Parking',
    description: 'Compact parking solution in Colombo 08, ideal for city center visits.',
    address: 'Borough Lane, Colombo 08',
    city: 'Colombo',
    district: 'Colombo',
    latitude: 6.9356,
    longitude: 79.8556,
    price_per_hour: 250,
    price_per_day: 1800,
    amenities: ['CCTV', 'Security'],
    vehicle_types: ['car', 'motorcycle'],
    total_spaces: 20,
    available_spaces: 8,
    operating_hours_start: '06:00',
    operating_hours_end: '21:00',
    is_24_hours: false,
    status: 'approved',
    verification_status: 'verified',
    rating: 4.4,
    review_count: 67,
  },
  // Kandy listings
  {
    id: 'seed-5',
    owner_id: 'owner-5',
    title: 'Kandy Mall Parking',
    description: 'Convenient parking at Kandy Mall, the largest shopping complex in Kandy.',
    address: 'Kandy Mall, Kandy',
    city: 'Kandy',
    district: 'Kandy',
    latitude: 7.2906,
    longitude: 80.6337,
    price_per_hour: 200,
    price_per_day: 1500,
    amenities: ['CCTV', 'Security', 'Elevator Access'],
    vehicle_types: ['car', 'motorcycle', 'van'],
    total_spaces: 100,
    available_spaces: 45,
    operating_hours_start: '08:00',
    operating_hours_end: '22:00',
    is_24_hours: false,
    status: 'approved',
    verification_status: 'verified',
    rating: 4.5,
    review_count: 234,
  },
  {
    id: 'seed-6',
    owner_id: 'owner-6',
    title: 'Kandy City Centre Parking',
    description: 'Underground parking at Kandy City Centre with direct mall access.',
    address: 'Kandy City Centre, Kandy',
    city: 'Kandy',
    district: 'Kandy',
    latitude: 7.2931,
    longitude: 80.6353,
    price_per_hour: 180,
    price_per_day: 1200,
    amenities: ['CCTV', 'Security', 'Covered'],
    vehicle_types: ['car', 'motorcycle'],
    total_spaces: 60,
    available_spaces: 28,
    operating_hours_start: '09:00',
    operating_hours_end: '21:00',
    is_24_hours: false,
    status: 'approved',
    verification_status: 'verified',
    rating: 4.3,
    review_count: 156,
  },
  // Negombo listings
  {
    id: 'seed-7',
    owner_id: 'owner-7',
    title: 'Negombo Beach Parking',
    description: 'Beach side parking for tourists visiting Negombo beach.',
    address: 'Beach Road, Negombo',
    city: 'Negombo',
    district: 'Gampaha',
    latitude: 7.2083,
    longitude: 79.8358,
    price_per_hour: 150,
    price_per_day: 1000,
    amenities: ['Security', 'Beach Access'],
    vehicle_types: ['car', 'motorcycle'],
    total_spaces: 25,
    available_spaces: 18,
    operating_hours_start: '06:00',
    operating_hours_end: '20:00',
    is_24_hours: false,
    status: 'approved',
    verification_status: 'verified',
    rating: 4.3,
    review_count: 67,
  },
  {
    id: 'seed-8',
    owner_id: 'owner-8',
    title: 'Negombo Lagoon Parking',
    description: 'Spacious parking area near Negombo Lagoon, great for nature lovers.',
    address: 'Lagoon Road, Negombo',
    city: 'Negombo',
    district: 'Gampaha',
    latitude: 7.2156,
    longitude: 79.8289,
    price_per_hour: 120,
    price_per_day: 800,
    amenities: ['Security'],
    vehicle_types: ['car', 'motorcycle', 'van'],
    total_spaces: 40,
    available_spaces: 22,
    operating_hours_start: '05:00',
    operating_hours_end: '19:00',
    is_24_hours: false,
    status: 'approved',
    verification_status: 'verified',
    rating: 4.1,
    review_count: 45,
  },
  // Galle listings
  {
    id: 'seed-9',
    owner_id: 'owner-9',
    title: 'Galle Fort Parking',
    description: 'Secure parking near the historic Galle Fort, UNESCO World Heritage Site.',
    address: 'Galle Fort, Galle',
    city: 'Galle',
    district: 'Galle',
    latitude: 6.0265,
    longitude: 80.2146,
    price_per_hour: 300,
    price_per_day: 2000,
    amenities: ['CCTV', 'Security', 'Covered'],
    vehicle_types: ['car', 'motorcycle'],
    total_spaces: 35,
    available_spaces: 10,
    operating_hours_start: '07:00',
    operating_hours_end: '22:00',
    is_24_hours: false,
    status: 'approved',
    verification_status: 'verified',
    rating: 4.7,
    review_count: 189,
  },
  {
    id: 'seed-10',
    owner_id: 'owner-10',
    title: 'Unawatuna Beach Parking',
    description: 'Parking near the famous Unawatuna Beach, popular with tourists.',
    address: 'Unawatuna, Galle',
    city: 'Galle',
    district: 'Galle',
    latitude: 6.0107,
    longitude: 80.2497,
    price_per_hour: 200,
    price_per_day: 1200,
    amenities: ['Security', 'Beach Access'],
    vehicle_types: ['car', 'motorcycle'],
    total_spaces: 30,
    available_spaces: 15,
    operating_hours_start: '06:00',
    operating_hours_end: '20:00',
    is_24_hours: false,
    status: 'approved',
    verification_status: 'verified',
    rating: 4.4,
    review_count: 98,
  },
  // Jaffna listings
  {
    id: 'seed-11',
    owner_id: 'owner-11',
    title: 'Jaffna City Parking',
    description: 'Central parking in Jaffna city, convenient for shopping and business.',
    address: 'Jaffna City Centre, Jaffna',
    city: 'Jaffna',
    district: 'Jaffna',
    latitude: 9.6615,
    longitude: 80.0255,
    price_per_hour: 150,
    price_per_day: 1000,
    amenities: ['CCTV', 'Security'],
    vehicle_types: ['car', 'motorcycle', 'van'],
    total_spaces: 45,
    available_spaces: 20,
    operating_hours_start: '07:00',
    operating_hours_end: '21:00',
    is_24_hours: false,
    status: 'approved',
    verification_status: 'verified',
    rating: 4.2,
    review_count: 76,
  },
  {
    id: 'seed-12',
    owner_id: 'owner-12',
    title: 'Jaffna Railway Station Parking',
    description: 'Parking near Jaffna Railway Station, ideal for commuters.',
    address: 'Railway Station Road, Jaffna',
    city: 'Jaffna',
    district: 'Jaffna',
    latitude: 9.6621,
    longitude: 80.0089,
    price_per_hour: 100,
    price_per_day: 600,
    amenities: ['Security'],
    vehicle_types: ['car', 'motorcycle'],
    total_spaces: 25,
    available_spaces: 12,
    operating_hours_start: '05:00',
    operating_hours_end: '23:00',
    is_24_hours: false,
    status: 'approved',
    verification_status: 'verified',
    rating: 4.0,
    review_count: 34,
  },
];

export const seedProfiles: Partial<Profile>[] = [
  {
    id: 'demo-user-1',
    email: 'demo@parkshare.lk',
    full_name: 'Demo User',
    phone: '+94771234567',
    nic: '199012345678',
    role: 'driver',
    is_verified: true,
    wallet_balance: 5000,
  },
];

export const seedVehicles: Partial<Vehicle>[] = [
  {
    id: 'vehicle-1',
    user_id: 'demo-user-1',
    make: 'Toyota',
    model: 'Corolla',
    year: 2020,
    license_plate: 'CAR-1234',
    color: 'Silver',
    vehicle_type: 'car',
    is_default: true,
  },
];

export const sriLankanCities = [
  'Colombo',
  'Kandy',
  'Galle',
  'Jaffna',
  'Negombo',
  'Kalmunai',
  'Anuradhapura',
  'Matale',
  'Trincomalee',
  'Jaffna',
  'Gampaha',
  'Puttalam',
  'Badulla',
  'Hambantota',
  'Mannar',
  'Polonnaruwa',
  'Batticaloa',
  'Mullaitivu',
  'Kilinochchi',
  'Vanni',
];

export const sriLankanDistricts = [
  'Colombo',
  'Gampaha',
  'Kalutara',
  'Kandy',
  'Matale',
  'Nuwara Eliya',
  'Galle',
  'Matara',
  'Hambantota',
  'Jaffna',
  'Kilinochchi',
  'Mannar',
  'Mullaitivu',
  'Vanni',
  'Batticaloa',
  'Ampara',
  'Trincomalee',
  'Polonnaruwa',
  'Anuradhapura',
  'Puttalam',
  'Kurunegala',
  'Pilibanda',
  'Badulla',
  'Monaragala',
  'Ratnapura',
  'Kegalle',
];

export const amenitiesList = [
  'CCTV',
  'Security',
  'Covered',
  'EV Charging',
  'Valet',
  'Car Wash',
  'Elevator',
  'Waiting Area',
  'Beach Access',
  'Wheelchair Access',
  '24/7 Access',
  'Night Parking',
];
